from __future__ import annotations

from decimal import Decimal
from pathlib import Path
from typing import Protocol

from fakturama_automation.domain.models import (
    Debtor,
    DebtorCandidate,
    DocumentRecord,
    InvoiceSnapshot,
    OrderInput,
    OrderItem,
    OrderSnapshot,
    Payment,
    PaymentMethodCandidate,
    ProductCandidate,
    VatCandidate,
)


class FakturamaGateway(Protocol):
    def preflight(self) -> None: ...

    def open_new_order(self) -> str: ...

    def set_order_header(self, order: OrderInput) -> None: ...

    def search_debtors(self, company_or_name: str) -> list[DebtorCandidate]: ...

    def cancel_active_dialog(self) -> None: ...

    def select_debtor(self, record_id: str) -> None: ...

    def read_selected_debtor(self) -> Debtor: ...

    def search_payment_methods(self, name: str) -> list[PaymentMethodCandidate]: ...

    def create_payment_method(self, payment: PaymentMethodCandidate) -> str: ...

    def open_new_debtor(self, debtor: Debtor) -> None: ...

    def discard_and_reopen_debtor(self, debtor: Debtor) -> None: ...

    def select_debtor_payment_method(self, payment_method: str) -> bool: ...

    def save_debtor(self) -> str: ...

    def search_vats(self, name: str) -> list[VatCandidate]: ...

    def create_vat(self, vat: VatCandidate) -> str: ...

    def search_products(self, sku: str) -> list[ProductCandidate]: ...

    def create_product(self, product: ProductCandidate) -> str: ...

    def add_product_to_order(self, record_id: str) -> int: ...

    def set_order_line(self, row_index: int, item: OrderItem) -> None: ...

    def complete_order(self) -> None: ...

    def read_order_snapshot(self) -> OrderSnapshot: ...

    def save_order(self) -> DocumentRecord: ...

    def verify_document(self, expected: DocumentRecord) -> DocumentRecord: ...

    def create_follow_up_invoice(self) -> str: ...

    def read_invoice_snapshot(self) -> InvoiceSnapshot: ...

    def set_invoice_payment(self, payment: Payment, invoice_total: Decimal) -> None: ...

    def save_invoice(self) -> DocumentRecord: ...

    def capture_screenshot(self, path: Path) -> bool: ...
